#include "RecoLocalCalo/HGCalRecAlgos/interface/HGCalCalibrationParameterHostCollectionRcd.h"
#include "FWCore/Framework/interface/eventsetuprecord_registration_macro.h"

EVENTSETUP_RECORD_REG(HGCalCalibrationParameterHostCollectionRcd);
