#include "DataFormats/Common/interface/Wrapper.h"
#include "DataFormats/PortableTestObjects/interface/TestHostCollection.h"
#include "DataFormats/PortableTestObjects/interface/TestSoA.h"
#include "DataFormats/PortableTestObjects/interface/TestHostRecHitCollection.h"
#include "DataFormats/PortableTestObjects/interface/TestRecHitSoA.h"
