#include "DataFormats/Common/interface/Wrapper.h"
#include "DataFormats/HGCalRecHit/interface/HGCalRecHitHostCollection.h"
#include "DataFormats/HGCalRecHit/interface/HGCalRecHitSoA.h"
#include "DataFormats/HGCalRecHit/interface/HGCalCalibrationParameterHostCollection.h"
#include "DataFormats/HGCalRecHit/interface/HGCalCalibrationParameterSoA.h"
